project_id = "wqqebuxglxphivghekyz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.kvk-search]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
